#!/usr/bin/env python3
"""Inject dependency-free BlackIndex utility controls into the local dashboard.

The core evidence dashboard is generated by evidence_map.py. This postprocessor
adds a small standalone research-console layer without changing evidence state:
quick workflow views, sorting, keyboard navigation, deep links, record copy/export
helpers, durable-object reference summaries, and links to the other local views.

No external JavaScript, CSS, framework, CDN, or network dependency is introduced.
"""
from __future__ import annotations

import sys
from pathlib import Path


STYLE = r'''
<!-- BLACKINDEX_UI_UTILITY -->
<style>
#bi-utility{display:flex;gap:7px;align-items:center;flex-wrap:wrap;margin-top:9px;padding-top:9px;border-top:1px solid var(--line)}
#bi-utility .bi-nav{display:flex;gap:5px;flex-wrap:wrap;margin-right:4px}
#bi-utility a,#bi-utility button,#bi-utility select{font:600 12px system-ui,Segoe UI,sans-serif;background:var(--panel2);color:var(--text);border:1px solid var(--line);border-radius:6px;padding:7px 9px;text-decoration:none;cursor:pointer}
#bi-utility a:hover,#bi-utility button:hover{border-color:#687887;background:#222b34}
#bi-utility button.bi-active{border-color:var(--accent);background:#26313a}
#bi-utility .bi-spacer{flex:1}
#bi-result-count{color:var(--muted);font-size:12px;white-space:nowrap}
#bi-key-help{position:fixed;right:16px;bottom:16px;z-index:9998;background:#101419;border:1px solid var(--line);border-radius:10px;padding:11px 13px;max-width:340px;box-shadow:0 10px 35px #0008;display:none}
#bi-key-help strong{display:block;margin-bottom:5px}.bi-kbd{display:inline-block;border:1px solid #4a5662;border-bottom-width:2px;border-radius:4px;padding:1px 5px;margin:1px 2px;background:#20262c;font-size:11px}
.bi-record-tools{display:flex;gap:6px;flex-wrap:wrap;margin:12px 0}
.bi-record-tools button,.bi-record-tools a{background:var(--panel2);color:var(--text);border:1px solid var(--line);border-radius:6px;padding:7px 9px;text-decoration:none;cursor:pointer;font:600 12px system-ui,Segoe UI,sans-serif}
.bi-record-tools button:hover,.bi-record-tools a:hover{border-color:#687887}
.bi-object-strip{margin:11px 0;padding:10px 12px;background:var(--panel);border:1px solid var(--line);border-radius:8px}
.bi-object-strip .bi-pills{display:flex;gap:5px;flex-wrap:wrap;margin-top:6px}.bi-pill{font-size:11px;padding:3px 7px;border:1px solid var(--line);border-radius:999px;background:var(--panel2);color:var(--muted)}
.bi-quick-label{color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.06em;margin-right:1px}
#bi-resume-review{position:fixed;right:16px;bottom:16px;z-index:9997;margin:0}
#bi-resume-review button{background:#151a20;color:#e7edf3;border:1px solid #46515c;border-radius:8px;padding:9px 11px;font:600 12px system-ui;cursor:pointer;box-shadow:0 7px 24px #0006}
#bi-resume-review button:hover{background:#222b34}
body.bi-help-open #bi-key-help{display:block}body.bi-help-open #bi-resume-review{display:none}
@media(max-width:850px){#bi-utility .bi-spacer{display:none}#bi-result-count{width:100%}.bi-record-tools{position:sticky;top:0;background:var(--bg);padding:7px 0;z-index:2}}
</style>
'''

SCRIPT = r'''
<script>
(function(){
  const header=document.querySelector('header');
  if(!header || document.getElementById('bi-utility')) return;

  const bar=document.createElement('div');
  bar.id='bi-utility';
  bar.innerHTML=`
    <div class="bi-nav">
      <a href="/work-queue.html">Work Queue</a>
      <a href="/source-lineage.html">Lineage</a>
      <a href="/entities.html">Entities</a>
    </div>
    <span class="bi-quick-label">View</span>
    <button type="button" data-bi-mode="all" class="bi-active">All</button>
    <button type="button" data-bi-mode="unreviewed">Unreviewed</button>
    <button type="button" data-bi-mode="missing">Missing refs</button>
    <button type="button" data-bi-mode="redaction">Redaction scored</button>
    <select id="bi-sort" title="Sort records">
      <option value="title">Sort: title</option>
      <option value="source">Sort: source</option>
      <option value="date-desc">Sort: newest date</option>
      <option value="date-asc">Sort: oldest date</option>
      <option value="archive-low">Sort: archive confidence ↑</option>
    </select>
    <span class="bi-spacer"></span>
    <span id="bi-result-count"></span>
    <button type="button" id="bi-help-btn" title="Keyboard shortcuts">?</button>`;
  header.appendChild(bar);

  const help=document.createElement('div');
  help.id='bi-key-help';
  help.innerHTML=`<strong>Keyboard shortcuts</strong>
    <div><span class="bi-kbd">/</span> search · <span class="bi-kbd">J</span>/<span class="bi-kbd">K</span> next/previous</div>
    <div><span class="bi-kbd">1</span>/<span class="bi-kbd">2</span>/<span class="bi-kbd">3</span> review/text/metadata</div>
    <div><span class="bi-kbd">C</span> copy record reference · <span class="bi-kbd">Esc</span> clear/close</div>
    <div class="sub" style="margin-top:6px">Selection and tab are stored in the URL hash, so a local view can be bookmarked.</div>`;
  document.body.appendChild(help);

  const resume=document.createElement('form');
  resume.id='bi-resume-review'; resume.method='post'; resume.action='/actions/resume-fbi-review'; resume.target='_blank';
  resume.innerHTML='<button type="submit">Resume FBI Review</button>';
  document.body.appendChild(resume);

  let mode='all';
  const baseRenderView=renderView;
  const baseRenderList=renderList;

  function isUnreviewed(d){ return !d.metadata.evidence_status || d.metadata.evidence_status==='unreviewed'; }
  function hasMissing(d){ return ((d.integrity||{}).missing_referenced_records||[]).length>0; }
  function hasRedactionScore(d){ const v=(d.integrity||{}).redaction_concern; return v!==null && v!==undefined && v!==''; }
  function docDate(d){ return String(d.metadata.document_date||d.metadata.year||''); }
  function titleOf(d){ return String(d.metadata.title||d.metadata.doc_id||''); }
  function sourceOf(d){ return String(d.metadata.source||''); }

  function matchesMode(d){
    if(mode==='unreviewed') return isUnreviewed(d);
    if(mode==='missing') return hasMissing(d);
    if(mode==='redaction') return hasRedactionScore(d);
    return true;
  }
  function compareDocs(a,b){
    const sort=document.getElementById('bi-sort').value;
    if(sort==='source') return sourceOf(a).localeCompare(sourceOf(b)) || titleOf(a).localeCompare(titleOf(b));
    if(sort==='date-desc') return docDate(b).localeCompare(docDate(a)) || titleOf(a).localeCompare(titleOf(b));
    if(sort==='date-asc') return docDate(a).localeCompare(docDate(b)) || titleOf(a).localeCompare(titleOf(b));
    if(sort==='archive-low'){
      const av=(a.integrity||{}).archive_confidence, bv=(b.integrity||{}).archive_confidence;
      return (av??99)-(bv??99) || titleOf(a).localeCompare(titleOf(b));
    }
    return titleOf(a).localeCompare(titleOf(b));
  }

  function utilityApply(){
    const q=document.getElementById('q').value.trim().toLowerCase();
    const s=document.getElementById('source').value;
    filtered=docs.filter(d=>(!s||d.metadata.source===s)&&matchesMode(d)&&(!q||searchable(d).toLowerCase().includes(q))).sort(compareDocs);
    if(current && !filtered.includes(current)) current=null;
    baseRenderList();
    const c=document.getElementById('bi-result-count');
    c.textContent=`${filtered.length} / ${docs.length} records`;
    if(current) renderView();
  }

  function linkedObjects(docId){
    const groups=(DATA.evidence_map&&DATA.evidence_map.objects)||{};
    const out=[];
    Object.entries(groups).forEach(([kind,items])=>{
      const matches=(items||[]).filter(x=>{
        try{return JSON.stringify(x).includes(docId)}catch(e){return false}
      });
      if(matches.length) out.push([kind,matches]);
    });
    return out;
  }
  function safeName(s){return String(s||'record').replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/^-|-$/g,'')||'record'}
  function download(name,text,type='application/json'){
    const a=document.createElement('a');
    a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.appendChild(a);a.click();
    setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},0);
  }
  async function copyText(text){
    try{await navigator.clipboard.writeText(text)}catch(e){
      const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();
    }
  }
  function recordReference(d){
    const m=d.metadata||{};
    return [m.doc_id,m.title,m.document_date||m.year,m.artifact_url||m.source_url,m.sha256?`SHA256 ${m.sha256}`:''].filter(Boolean).join(' · ');
  }
  function syncHash(){
    if(!current)return;
    const p=new URLSearchParams();p.set('doc',current.metadata.doc_id);p.set('tab',tab);
    history.replaceState(null,'','#'+p.toString());
  }
  function enhanceCurrentView(){
    if(!current)return;
    const view=document.getElementById('view');
    const firstPre=view.querySelector('pre');
    if(!firstPre || view.querySelector('.bi-record-tools')){syncHash();return;}
    const m=current.metadata||{};
    const tools=document.createElement('div');tools.className='bi-record-tools';
    tools.innerHTML=`<button type="button" data-bi-copy="ref">Copy reference</button><button type="button" data-bi-copy="id">Copy ID</button><button type="button" data-bi-export>Export record</button>${m.artifact_url?'<a target="_blank" rel="noopener" href="'+esc(m.artifact_url)+'">Open source ↗</a>':''}`;
    firstPre.parentNode.insertBefore(tools,firstPre);
    tools.querySelector('[data-bi-copy="ref"]').onclick=()=>copyText(recordReference(current));
    tools.querySelector('[data-bi-copy="id"]').onclick=()=>copyText(m.doc_id||'');
    tools.querySelector('[data-bi-export]').onclick=()=>{
      const refs=linkedObjects(m.doc_id).flatMap(([kind,items])=>items.map(object=>({kind,object})));
      const pack={exported_at:new Date().toISOString(),document:current.metadata,integrity:current.integrity,review_markdown:current.extraction,text_chunk:current.text,durable_object_references:refs};
      download(safeName(m.doc_id)+'.blackindex.json',JSON.stringify(pack,null,2));
    };
    const links=linkedObjects(m.doc_id);
    const strip=document.createElement('div');strip.className='bi-object-strip';
    const total=links.reduce((n,x)=>n+x[1].length,0);
    strip.innerHTML=`<div><strong>Durable object references</strong> <span class="sub">${total} linked object${total===1?'':'s'}</span></div><div class="bi-pills">${links.length?links.map(([kind,items])=>`<span class="bi-pill">${esc(kind.replaceAll('_',' '))}: ${items.length}</span>`).join(''):'<span class="bi-pill">none encoded</span>'}</div><div class="sub" style="margin-top:6px">Reference count is navigational only; it does not imply corroboration, importance, or culpability.</div>`;
    tools.parentNode.insertBefore(strip,tools.nextSibling);
    syncHash();
  }

  renderView=function(){baseRenderView();enhanceCurrentView()};
  renderList=function(){baseRenderList();document.getElementById('bi-result-count').textContent=`${filtered.length} / ${docs.length} records`;};

  document.querySelectorAll('[data-bi-mode]').forEach(b=>b.onclick=()=>{
    mode=b.dataset.biMode;document.querySelectorAll('[data-bi-mode]').forEach(x=>x.classList.toggle('bi-active',x===b));utilityApply();
  });
  document.getElementById('bi-sort').onchange=utilityApply;
  document.getElementById('q').oninput=utilityApply;
  document.getElementById('source').onchange=utilityApply;
  document.getElementById('clear').onclick=()=>{document.getElementById('q').value='';document.getElementById('source').value='';mode='all';document.querySelectorAll('[data-bi-mode]').forEach(x=>x.classList.toggle('bi-active',x.dataset.biMode==='all'));utilityApply()};
  document.getElementById('bi-help-btn').onclick=()=>document.body.classList.toggle('bi-help-open');

  function selectOffset(delta){
    if(!filtered.length)return;
    let i=current?filtered.indexOf(current):-1;i=Math.max(0,Math.min(filtered.length-1,i+delta));current=filtered[i];tab='extraction';renderList();renderView();
    const active=document.querySelector('#list .item.active');if(active)active.scrollIntoView({block:'nearest'});
  }
  document.addEventListener('keydown',e=>{
    const tag=(e.target.tagName||'').toLowerCase();const typing=tag==='input'||tag==='textarea'||tag==='select';
    if(e.key==='Escape'){document.body.classList.remove('bi-help-open');if(typing){e.target.blur();return}document.getElementById('q').value='';utilityApply();return}
    if(typing)return;
    if(e.key==='/'){e.preventDefault();document.getElementById('q').focus();return}
    if(e.key==='j'||e.key==='J'){e.preventDefault();selectOffset(1);return}
    if(e.key==='k'||e.key==='K'){e.preventDefault();selectOffset(-1);return}
    if(current && ['1','2','3'].includes(e.key)){tab=e.key==='1'?'extraction':e.key==='2'?'text':'metadata';renderView();return}
    if(current && (e.key==='c'||e.key==='C')){copyText(recordReference(current));return}
  });

  function restoreHash(){
    const p=new URLSearchParams(location.hash.replace(/^#/,''));const id=p.get('doc'),wanted=p.get('tab');
    if(!id)return;const d=docs.find(x=>x.metadata.doc_id===id);if(!d)return;current=d;tab=['extraction','text','metadata'].includes(wanted)?wanted:'extraction';renderList();renderView();
  }
  utilityApply();restoreHash();
})();
</script>
'''


def main() -> int:
    path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("local/dashboard/blackindex-dashboard.html")
    if not path.is_file():
        print(f"error: dashboard not found: {path}", file=sys.stderr)
        return 2

    text = path.read_text(encoding="utf-8")
    if "<!-- BLACKINDEX_UI_UTILITY -->" not in text:
        head_end = text.lower().find("</head>")
        if head_end >= 0:
            text = text[:head_end] + STYLE + text[head_end:]
        else:
            text = STYLE + text

        body_end = text.lower().rfind("</body>")
        if body_end >= 0:
            text = text[:body_end] + SCRIPT + text[body_end:]
        else:
            text += SCRIPT

    path.write_text(text, encoding="utf-8")
    print(f"Dashboard standalone utility layer injected: {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
