#!/usr/bin/env python3
"""Compile BlackIndex source genealogy / evidence lineage.

The compiler turns durable source_dependency objects and document-level lineage
metadata into a directed graph. It also groups sources sharing the same declared
upstream dependency so derivative repetition can be seen as one evidentiary
lineage instead of accidental independent corroboration.

No historical conclusion is generated by this tool.
"""
from __future__ import annotations

import argparse
import json
import os
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ROOT = Path(os.environ.get("BLACKINDEX_ROOT", REPO_ROOT))


def now():
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def read(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def metadata(root: Path):
    result = {}
    for p in sorted((root / "metadata").glob("*.json")):
        try:
            d = read(p)
        except Exception:
            continue
        if d.get("doc_id"):
            result[d["doc_id"]] = d
    return result


def main() -> int:
    ap = argparse.ArgumentParser(description="Compile BlackIndex source lineage")
    ap.add_argument("--root", default=str(DEFAULT_ROOT))
    args = ap.parse_args()
    root = Path(args.root).resolve()
    docs = metadata(root)
    nodes = {}
    edges = []

    for doc_id, m in docs.items():
        nodes[doc_id] = {
            "id": doc_id,
            "kind": "document",
            "title": m.get("title") or doc_id,
            "source": m.get("source"),
            "collection": m.get("collection"),
            "document_date": m.get("document_date"),
            "sha256": m.get("sha256"),
        }
        parent = m.get("parent_container_doc_id")
        if parent:
            edges.append({
                "from": doc_id,
                "to": parent,
                "relationship": "extracted-from-parent-container",
                "independence": "dependent",
                "origin": "metadata",
                "page_range": m.get("parent_page_range"),
            })
        for dep in m.get("source_dependencies") or []:
            if isinstance(dep, dict):
                target = dep.get("parent_doc_id") or dep.get("source_id") or dep.get("depends_on")
                if target:
                    edges.append({
                        "from": doc_id,
                        "to": target,
                        "relationship": dep.get("type") or "declared-source-dependency",
                        "independence": dep.get("independence") or "dependent",
                        "origin": "metadata",
                    })

    for p in sorted((root / "objects/source_dependencies").glob("*.json")):
        try:
            d = read(p)
        except Exception:
            continue
        source = d.get("source_id")
        target = d.get("depends_on")
        if not source or not target:
            continue
        if source not in nodes:
            nodes[source] = {"id": source, "kind": "source_or_synthesis", "title": source}
        if target not in nodes:
            nodes[target] = {"id": target, "kind": "source_or_lineage", "title": target}
        edges.append({
            "from": source,
            "to": target,
            "relationship": d.get("dependency_type") or "source-dependency",
            "independence": d.get("independence") or "unknown",
            "assertion_id": d.get("assertion_id"),
            "object_id": d.get("object_id"),
            "origin": "source_dependency_object",
        })

    # Exact-edge de-duplication prevents metadata + object indexing from visually
    # multiplying the same dependency.
    unique = []
    seen = set()
    for e in edges:
        key = (e.get("from"), e.get("to"), e.get("relationship"), e.get("assertion_id"))
        if key not in seen:
            seen.add(key)
            unique.append(e)
    edges = unique

    upstream = defaultdict(list)
    for e in edges:
        upstream[e["to"]].append(e)
    families = []
    for target, members in sorted(upstream.items()):
        sources = sorted({e["from"] for e in members})
        if len(sources) < 2:
            continue
        families.append({
            "upstream_source": target,
            "member_sources": sources,
            "member_count": len(sources),
            "warning": "Shared upstream lineage: do not count member sources as fully independent without additional evidence.",
        })

    independence_counts = defaultdict(int)
    for e in edges:
        independence_counts[e.get("independence") or "unknown"] += 1

    payload = {
        "schema_version": 1,
        "generated_at": now(),
        "purpose": "source genealogy / evidence lineage; not a verdict or corroboration score",
        "nodes": sorted(nodes.values(), key=lambda x: x["id"]),
        "edges": edges,
        "shared_lineage_families": families,
        "counts": {
            "nodes": len(nodes),
            "edges": len(edges),
            "shared_lineage_families": len(families),
            "independence": dict(sorted(independence_counts.items())),
        },
    }
    out_dir = root / "local/index"
    out_dir.mkdir(parents=True, exist_ok=True)
    json_path = out_dir / "source-lineage.json"
    json_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")

    lines = [
        "# BlackIndex Source Lineage Report", "",
        "> Source genealogy only. Repetition through a shared upstream source is not independent corroboration.", "",
        f"Nodes: **{len(nodes)}** · Edges: **{len(edges)}** · Shared-lineage families: **{len(families)}**", "",
        "## Shared upstream lineages", "",
    ]
    if families:
        for f in families:
            lines += [f"### `{f['upstream_source']}`", "", "Derived/reliant sources:", ""]
            lines += [f"- `{s}`" for s in f["member_sources"]]
            lines += ["", f"**Caution:** {f['warning']}", ""]
    else:
        lines += ["No multi-source shared upstream lineage is currently encoded.", ""]
    lines += ["## Dependency edges", "", "| Source | Relationship | Depends on | Independence |", "|---|---|---|---|"]
    for e in edges:
        lines.append(f"| `{e['from']}` | {e.get('relationship','')} | `{e['to']}` | {e.get('independence','unknown')} |")
    md_path = out_dir / "source-lineage.md"
    md_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(json.dumps({"json": str(json_path), "markdown": str(md_path), **payload["counts"]}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
